# Generated by Django 5.1.7 on 2025-03-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
