# Generated by Django 5.1.7 on 2025-03-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0002_todo_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_active',
        ),
    ]
